### ISSUE TITLE
Minor layout problem

### ISSUE THREAD

**Issue by marsamak** [catalinac3/weather-app#24]
![image](https://user-images.githubusercontent.com/7361924/96923777-08d76480-14b2-11eb-8918-7a944175ee99.png)
Hier this search buttom with magnifier overlaps the Input element a bit.

**Comment by marsamak** [comment]
![image](https://user-images.githubusercontent.com/7361924/96924370-d8dc9100-14b2-11eb-80f9-a0b46a96b5de.png)

**Comment by catalinac3** [comment]
yes, you are right, it is a characteristic of inline form in bootstrap that I use there, maybe I got back to using and input-group, or I do it manually, not sure...
"Controls only appear inline in viewports that are at least 576px wide to account for narrow viewports on mobile devices." from 
https://getbootstrap.com/docs/4.0/components/forms/
