### ISSUE TITLE
Change handling of "User denied Geolocation" exception

### ISSUE THREAD

**Issue by marsamak** [catalinac3/weather-app#26]
![image](https://user-images.githubusercontent.com/7361924/96924665-4688bd00-14b3-11eb-9c49-b8b1515ad91c.png)

When I deny the Share geolocation request, the app shows no information at all (after I close the alert window).
![image](https://user-images.githubusercontent.com/7361924/96924906-9ff0ec00-14b3-11eb-9c1a-e81e8bc289d3.png)

MB it would be a better option to show information for some default city (Berlin or smth else) in case the user geolocation is unknown?

**Comment by catalinac3** [comment]
I like this Idea, now that I have the city search makes total sense :)
