### ISSUE TITLE
Two functions do the same, get rid of one of them

### ISSUE THREAD

**Issue by marsamak** [catalinac3/weather-app#28]
In [jsFiles/app.js](https://github.com/catalinac3/weather-app/blob/master/jsFiles/app.js):

```javascript
function handleError(error) {
  alertError(error);
}
```
means there is no difference between your `handleError` and `alertError` functions. Supposedly you'd better leave just one of them.

**Comment by catalinac3** [comment]
yes, this issue has been addressed Originally posted by @oktupol in #20 (comment), and it has been fixed on my current pull request - not approved yet. Although I think in the future, this is the place for the default city when the user denies the location :)
