### ISSUE TITLE
Wireframe homework

### ISSUE THREAD

**Issue by catalinac3** [catalinac3/weather-app#3]
Here is my wireframe, my idea is that I should focus on part done with a blue pencil.
Then I would continue to the parts bellow (if time allows). 

![wireframe](https://user-images.githubusercontent.com/56088689/93523802-ddea7580-f933-11ea-9c9e-190e5bc82856.jpg) @MrTim @keponk @Vailoivan (I don't think this works for the third teacher)

**Comment by MrTim** [comment]
Nice structuring! For me it's really clear how your idea should looks like :)

**Comment by catalinac3** [comment]
Great, thanks @MrTim
